server:
  port: 8083

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb+srv://luiz:study123@purchase-service.5aw57.mongodb.net/purchase?retryWrites=true&w=majority

integration:
  customer:
    url: http://localhost:8080
  product:
    url: http://localhost:8081